# test yaml

model_name: "osp_next"
pipeline_name: "t2v"
seed: 1024

prompt_txt: "assets/t2v/simple_prompts.txt"
output_dir: "/path/to/output"

num_frames: 81
height: 720
width: 1280
save_fps: 16
batch_size: 1

fsdp_size: 8
sp_size: 4
skiparse_sp_size: 4
use_sequence_parallel: False
use_skiparse_sequence_parallel: True
reshard_after_forward: Null
explicit_prefetching_num_blocks: 2
weight_dtype: "bf16"
save_with_dcp_api: False

model_config:
  dim: 5120
  ffn_dim: 13824
  freq_dim: 256
  in_dim: 16
  num_heads: 40
  num_layers: 40
  out_dim: 16
  text_len: 512
  skiparse_model_type: "dual_end"
  sparse_ratio: 2
  num_full_blocks: 8
  pretrained_model_dir_or_checkpoint: "/path/to/model"

scheduler_config:
  scheduler_name: "flow_matching"
  num_inference_steps: 50
  shift: 7.0
  guidance_scale: 5.0

vae_config:
  vae_path: "/path/to/vae"
  dtype: "fp32"

text_encoder_config:
  text_len: 512
  checkpoint_path: "/path/to/text_encoder"
  text_tokenizer_path: "/path/to/text_tokenizer"
  use_fsdp: True
